### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DjsProject** [devz3ro/Arc-Windows-10-Native#1]
Chocolatey is already installed. Skipping installation.
xdelta3 is already installed. Skipping installation.
Downloading file from https://releases.arc.net/windows/ArcInstaller.exe to C:\Users\1\Downloads\ArcInstaller.exe...                                                                                                                     Expected v1.0.1.0 MD5: 930d75cd4b6e69fd38ee9f53cb3a8721
Found MD5: f4681c38e0505e3cf383726c470ab363
MD5 checksum verification failed. Expected: 930d75cd4b6e69fd38ee9f53cb3a8721, Got: f4681c38e0505e3cf383726c470ab363
Press Enter to exit ...

**Comment by mizifih** [comment]
The new MD5 hash is `F4681C38E0505E3CF383726C470AB363`, the PowerShell code expect `930d75cd4b6e69fd38ee9f53cb3a8721`. Also, since the origin was changed, I have no idea how to calculate the expected final hash.

**Comment by devz3ro** [comment]
I will update it to the new version, they released 1.1.0.0

**Comment by devz3ro** [comment]
Just updated the script to reflect the new version, give this a try:

https://github.com/devz3ro/Arc-Windows-10-Native/releases/tag/ArcWindows10NativeInstaller-1.1.0.0

**Comment by mizifih** [comment]
Yes, it worked completely. The browser is running. Thank you <3
