### ISSUE TITLE
Not updating from 1.3.2 to 1.3.3

### ISSUE THREAD

**Issue by whur** [devz3ro/Arc-Windows-10-Native#2]
The arc installer is not updating my build from 1.3.2 to 1.3.3 after running the batch file and the installer. Perhaps I should try the non native to update? Or perhaps the current installer is just a 1.3.2 version.

**Comment by devz3ro** [comment]
Either 1.3.3 is a typo from the Arc team or they pulled it. I noticed myself that 1.3.3 is mentioned at the page shown below, but even on my Windows 11 PC 1.3.2 is the latest available version when I check for updates.

https://resources.arc.net/hc/en-us/articles/22513842649623-Arc-for-Windows-2023-2024-Release-Notes

**Comment by whur** [comment]
I noticed this at the bottom of the release notes:

"Arc 1.3.3 updates to Chromium 125.0.6422.113"

And verified that my chromium is still on .112

I guess I'll wait for the binary to update as this must be issue on Arc's side. Thanks for this project.

**Comment by jasonliul** [comment]
v 1.3.3 just release today
https://releases.arc.net/windows/prod/1.3.3.30647/Arc.x64.msix
